version: "3.7"

services:
  db:
    image: postgres:14.1-alpine
    container_name: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./pg_data:/usr/src/postgresql/data
    environment:
      POSTGRES_DB: ssstatistics
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /usr/src/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 3s
      retries: 5
    restart: always
  projecttau:
    build: .
    container_name: projecttau
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    environment:
      BASE_URL: ""
      POSTGRES_HOST: 65.108.8.160
      POSTGRES_PORT: 9999
      POSTGRES_DB: ssstatistics
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: MoM4eezei5eewal
    restart: always
  forecast-service:
    build:
      context: ./internal/service/sarima
    ports:
      - "5000:5000"
    restart: always
