# remove -example from the file name
db:
  host: localhost
  user: postgres
  password: postgres
  dbname: ssstatistics
  port: 5432

admin:
  login: admin
  password: 1234

telegram:
  token: fawfabaw123
  trustedChatIDs: [12314141, 1321313]

secret:
  crawlBlacklist: ["amogus", "aboba"]

proxy: 127.0.0.1

